changelog:
   exclude:
     labels:
       - ignore-for-release
     authors:
       - dependabot
   categories:
     - title: Bug Fixes
       labels:
         - bug
     - title: Enhancements
       labels:
         - enhancement
     - title: Tiger Edges
       labels:
         - tiger_edges
     - title: Observations
       labels:
         - observations
     - title: B Changes
       labels:
         - B
     - title: A Changes
       labels:
         - A
     - title: Other Changes
       labels:
         - "*"
