 name: tigernet
 channels:
   - conda-forge
 dependencies:
   - python=3.9
   - black
   - geopandas>=0.9.0
   - ipython
   - jupyter
   - libpysal
   - matplotlib
   - nb_conda_kernels
   - numpy
   - pandas
   - pip
   - pre-commit
   - pygeos>=0.8.0
   - scipy
   - shapely>=1.7.1
   - watermark
   - pip:
     - git+https://github.com/jGaboardi/tigernet.git@main
     - handcalcs
