 name: tigernet
 channels:
   - conda-forge
 dependencies:
   - python=3.8
   - black
   - descartes
   - geopandas>=0.8.0
   - ipython
   - jupyter
   - libpysal>=4.3
   - matplotlib
   - nb_conda_kernels
   - numpy>=1.3
   - pandas>=1.0
   - pip
   - pre-commit
   - scipy
   - shapely>=1.7.1
   - watermark
   - pip:
     - git+https://github.com/jGaboardi/tigernet.git@master
     - handcalcs
