 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 45
     strategy:
       matrix:
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         environment-file: [ci/37.yaml, ci/38.yaml, ci/39.yaml]
     defaults:
       run:
         shell: bash -l {0}
     steps:
       - uses: actions/checkout@v2
       - uses: conda-incubator/setup-miniconda@v2
         with:
            miniconda-version: 'latest'
            mamba-version: "*"
            channels: conda-forge,defaults
            auto-update-conda: false
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
       - run: conda info --all
       - run: conda list
       - run: python -m black . --check
       - run: pytest -v tigernet --cov=tigernet --doctest-modules --cov-config=.coveragerc --cov-report=xml
       - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: tigernet-codecov

