 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 10
     strategy:
       matrix:
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         environment-file: [ci/36.yaml, ci/37.yaml, ci/38.yaml]
     steps:
       - uses: actions/checkout@v2
       - uses: goanpeca/setup-miniconda@v1
         with:
            miniconda-version: 'latest'
            auto-update-conda: true
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
       - shell: bash -l {0}
         run: conda update -n base -c defaults conda
       - shell: bash -l {0}
         run: conda info --all
       - shell: bash -l {0}
         run: conda list
       - uses: jpetrucciani/black-check@20.8b1
         with:
           path: 'tigernet/'
       - shell: bash -l {0}
         run: py.test -v tigernet --cov=tigernet --doctest-modules --cov-config=.coveragerc --cov-report=xml
       - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
         uses: codecov/codecov-action@v1.0.13
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: tigernet-codecov

