 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 45
     strategy:
       matrix:
         environment-file: [.ci/38.yaml, .ci/39.yaml, .ci/310.yaml]
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
     
     steps:
       - name: checkout repo
         uses: actions/checkout@v2
       
       - name: setup micromamba
         uses: mamba-org/provision-with-micromamba@main
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
       
       - name: run tests - bash
         shell: bash -l {0}
         run: pytest -v tigernet --cov=tigernet --doctest-modules --cov-config=.coveragerc --cov-report=xml
         if: matrix.os != 'windows-latest'
       
       - name: run tests - powershell
         shell: powershell
         run: pytest -v tigernet --cov=tigernet --doctest-modules --cov-config=.coveragerc --cov-report=xml
         if: matrix.os == 'windows-latest'
       
       - name: codecov
         uses: codecov/codecov-action@v2
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: tigernet-codecov
